name = "petition"
main = "./functions/index.ts"
compatibility_date = "2025-04-23"
compatibility_flags = ["nodejs_compat"]

assets = { not_found_handling = "single-page-application", run_worker_first = [
  "/api/*",
  "/auth/*",
] }

# route = { pattern = "petition.ph/*", zone_name = "petition.ph" }

[vars]
# Auth.js environment variables (set these in Cloudflare Workers dashboard or use wrangler secret)
# AUTH_SECRET = "your-secret-here"
# GOOGLE_CLIENT_ID = "your-google-client-id"
# FACEBOOK_CLIENT_ID = "your-facebook-app-id"

# For secrets (use: wrangler secret put VARIABLE_NAME)
# - AUTH_SECRET
# - GOOGLE_CLIENT_SECRET
# - FACEBOOK_CLIENT_SECRET

[[d1_databases]]
binding = "DB"
database_name = "petition-db"
# database_id = "4fd4c724-020d-4eed-b3e7-959c8f38a786"
database_id = "c59456f6-7137-4c00-a3c7-e9c56ccd820e"

[env.staging]
name = "petition-staging"
